name = "hi"
main = "src/index.js"

compatibility_date = "2022-08-08"

routes = [
	{ pattern = "work.muedsa.com", custom_domain = true },
	{ pattern = "worker.muedsa.com", custom_domain = true }
]

[vars]
DEBUG_SECRET = "233"
